commands:
    build:
        description: |
            Build new image
        parameters:
            dockerfile:
                default: Dockerfile
                description: Name of the dockerfile to be used. Defaults to Dockerfile.
                type: string
            module_name:
                default: $CIRCLE_PROJECT_REPONAME
                description: Name of the module in Humanitec. The id must be all lowercase letters, numbers and the "-" symbol. It cannot start or end with "-". Defaults to $CIRCLE_PROJECT_REPONAME.
                type: string
            organization:
                default: ""
                description: Name of the organization in Humanitec.
                type: string
            path:
                default: .
                description: Path to the directory containing the dockerfile. Default to . (working directory).
                type: string
        steps:
            - run:
                command: |
                    LOCAL_TAG=<< parameters.organization >>/<< parameters.module_name >>:$CIRCLE_SHA1
                    docker build \
                      -t $LOCAL_TAG \
                      -f << parameters.path >>/<< parameters.dockerfile >> \
                      << parameters.path >>
                name: Build docker image
    build-push-and-notify:
        description: |
            Build image and push it to the Humanitec registry
        parameters:
            checkout_submodules:
                default: false
                description: Option to checkout git submodules. Defaults to false.
                type: boolean
            dockerfile:
                default: Dockerfile
                description: Name of the dockerfile to be used. Defaults to Dockerfile.
                type: string
            humanitec_api:
                default: https://api.humanitec.io
                description: URL of the API to be used. Defaults to https://api.humanitec.io.
                type: string
            humanitec_token:
                default: HUMANITEC_TOKEN
                description: Token to access Humanitec. Needs to be set in an environment variable in the project.
                type: env_var_name
            module_name:
                default: $CIRCLE_PROJECT_REPONAME
                description: Name of the module in Humanitec. The id must be all lowercase letters, numbers and the "-" symbol. It cannot start or end with "-". Defaults to $CIRCLE_PROJECT_REPONAME.
                type: string
            organization:
                default: ""
                description: Name of the organization in Humanitec.
                type: string
            path:
                default: .
                description: Path to the directory containing the dockerfile. Default to . (working directory).
                type: string
        steps:
            - checkout
            - when:
                condition: << parameters.checkout_submodules >>
                steps:
                    - run: git submodule sync
                    - run: git submodule update --init --recursive
            - check_namings:
                module_name: << parameters.module_name >>
            - build:
                dockerfile: << parameters.dockerfile >>
                module_name: << parameters.module_name >>
                organization: << parameters.organization >>
                path: << parameters.path >>
            - push-and-notify:
                humanitec_api: << parameters.humanitec_api >>
                module_name: << parameters.module_name >>
                organization: << parameters.organization >>
    check_namings:
        description: |
            Check whether selected names are valid in Humanitec.
        parameters:
            module_name:
                default: $CIRCLE_PROJECT_REPONAME
                description: Name of the module in Humanitec. The id must be all lowercase letters, numbers and the "-" symbol. It cannot start or end with "-". Defaults to $CIRCLE_PROJECT_REPONAME.
                type: string
        steps:
            - run:
                command: |
                    if ! echo "<< parameters.module_name >>" | grep -q '^[a-z0-9][a-z0-9-]*[a-z0-9]$'
                    then
                      echo "module_name: \"<< parameters.module_name >>\" is not valid."
                      echo "module_name must be all lowercase letters, numbers and the \"-\" symbol. It cannot start or end with \"-\"."
                      exit 1
                    fi
                name: Check module name
    notify:
        description: |
            Notify Humanitec about a new available build
        parameters:
            humanitec_api:
                default: https://api.humanitec.io
                description: URL of the API to be used. Defaults to https://api.humanitec.io.
                type: string
            humanitec_token:
                default: HUMANITEC_TOKEN
                description: Token to access Humanitec. Needs to be set in an environment variable in the project.
                type: env_var_name
            image_name:
                default: ""
                description: Name of the image.
                type: string
            module_name:
                default: $CIRCLE_PROJECT_REPONAME
                description: Name of the module in Humanitec. The id must be all lowercase letters, numbers and the "-" symbol. It cannot start or end with "-". Defaults to $CIRCLE_PROJECT_REPONAME.
                type: string
            organization:
                default: ""
                description: Name of the organization in Humanitec.
                type: string
        steps:
            - check_namings:
                module_name: << parameters.module_name >>
            - run:
                command: |
                    curl -X POST \
                      -H "Authorization: Bearer ${<< parameters.humanitec_token >>}" \
                      -H "Content-type: application/json" \
                      -d "{\"commit\": \"$CIRCLE_SHA1\", \"branch\": \"$CIRCLE_BRANCH\", \"image\": \"<< parameters.image_name >>\"}" \
                      << parameters.humanitec_api >>/orgs/<< parameters.organization >>/modules/<< parameters.module_name >>/builds
                name: Notify Humanitec
    push-and-notify:
        description: |
            Push docker image to the Humanitec registry
        parameters:
            humanitec_api:
                default: https://api.humanitec.io
                description: URL of the API to be used. Defaults to https://api.humanitec.io.
                type: string
            humanitec_token:
                default: HUMANITEC_TOKEN
                description: Token to access Humanitec. Needs to be set in an environment variable in the project.
                type: env_var_name
            module_name:
                default: $CIRCLE_PROJECT_REPONAME
                description: Name of the module in Humanitec. The id must be all lowercase letters, numbers and the "-" symbol. It cannot start or end with "-". Defaults to $CIRCLE_PROJECT_REPONAME.
                type: string
            organization:
                default: ""
                description: Name of the organization in Humanitec.
                type: string
        steps:
            - check_namings:
                module_name: << parameters.module_name >>
            - run:
                command: |
                    curl -X GET \
                      -s -v \
                      -H "Authorization: Bearer ${<< parameters.humanitec_token >>}" \
                      -H "accept: application/json" \
                      << parameters.humanitec_api >>/orgs/<< parameters.organization >>/registries/humanitec/creds > creds.json

                    echo "export REGISTRY_PASSWORD=$(cat creds.json | jq -r '.password')" >> $BASH_ENV
                    echo "export REGISTRY_USERNAME=$(cat creds.json | jq -r '.username')" >> $BASH_ENV
                    echo "export REGISTRY_REGISTRY=$(cat creds.json | jq -r '.registry')" >> $BASH_ENV
                name: Get credentials for the Humanitec registry
            - run:
                command: |
                    LOCAL_TAG=<< parameters.organization >>/<< parameters.module_name >>:$CIRCLE_SHA1
                    REMOTE_TAG=$REGISTRY_REGISTRY/$LOCAL_TAG
                    echo "export REMOTE_TAG=$REMOTE_TAG" >> $BASH_ENV

                    docker login --username $REGISTRY_USERNAME --password $REGISTRY_PASSWORD $REGISTRY_REGISTRY
                    docker tag $LOCAL_TAG $REMOTE_TAG
                    docker push $REMOTE_TAG
                name: Log into the Humanitec registry and push the image
            - notify:
                humanitec_api: << parameters.humanitec_api >>
                image_name: $REMOTE_TAG
                module_name: << parameters.module_name >>
                organization: << parameters.organization >>
description: |
    Build and push new images to Humanitec and improve maintenance of your Kubernetes-ready applications after every CircleCI build. Experience seamless continuous delivery during your development process.
display:
    home_url: https://humanitec.com
    source_url: https://github.com/Humanitec/humanitec-orb
examples:
    simple-build-push-and-notify:
        description: |
            Build an image from your repository and push it to Humanitec.
        usage:
            orbs:
                humanitec: humanitec/humanitec@volatile
            version: 2.1
            workflows:
                build-push-and-notify-humanitec:
                    jobs:
                        - humanitec/build-push-and-notify-humanitec:
                            organization: humanitec-organization
executors:
    default:
        description: |
            CircleCI's Ubuntu-based machine executor VM: https://circleci.com/docs/2.0/executor-types/#using-machine
        machine:
            docker_layer_caching: << parameters.use-docker-layer-caching >>
            image: << parameters.image >>
        parameters:
            image:
                default: ubuntu-1604:201903-01
                type: string
            use-docker-layer-caching:
                default: false
                type: boolean
jobs:
    build-push-and-notify-humanitec:
        description: |
            Build new image, push it to the Humanitec registry and notify Humanitec about the new build.
        executor: default
        parameters:
            checkout_submodules:
                default: false
                description: Option to checkout git submodules. Defaults to false.
                type: boolean
            dockerfile:
                default: Dockerfile
                description: Name of the dockerfile to be used. Defaults to Dockerfile.
                type: string
            humanitec_api:
                default: https://api.humanitec.io
                description: URL of the API to be used. Defaults to https://api.humanitec.io.
                type: string
            humanitec_token:
                default: HUMANITEC_TOKEN
                description: Token to access Humanitec. Needs to be set in an environment variable in the project.
                type: env_var_name
            module_name:
                default: $CIRCLE_PROJECT_REPONAME
                description: Name of the module in Humanitec. The id must be all lowercase letters, numbers and the "-" symbol. It cannot start or end with "-". Defaults to $CIRCLE_PROJECT_REPONAME.
                type: string
            organization:
                default: ""
                description: Name of the organization in Humanitec.
                type: string
            path:
                default: .
                description: Path to the directory containing the dockerfile. Default to . (working directory).
                type: string
        steps:
            - build-push-and-notify:
                checkout_submodules: << parameters.checkout_submodules >>
                dockerfile: << parameters.dockerfile >>
                humanitec_api: << parameters.humanitec_api >>
                module_name: << parameters.module_name >>
                organization: << parameters.organization >>
                path: << parameters.path >>
    notify-humanitec:
        description: |
            Notify Humanitec about new build
        executor: default
        parameters:
            humanitec_api:
                default: https://api.humanitec.io
                description: URL of the API to be used. Defaults to https://api.humanitec.io.
                type: string
            humanitec_token:
                default: HUMANITEC_TOKEN
                description: Token to access Humanitec. Needs to be set in an environment variable in the project.
                type: env_var_name
            image_name:
                default: ""
                description: Name of the image.
                type: string
            module_name:
                default: $CIRCLE_PROJECT_REPONAME
                description: Name of the module in Humanitec. The id must be all lowercase letters, numbers and the "-" symbol. It cannot start or end with "-". Defaults to $CIRCLE_PROJECT_REPONAME.
                type: string
            organization:
                default: ""
                description: Name of the organization in Humanitec.
                type: string
        steps:
            - notify:
                humanitec_api: << parameters.humanitec_api >>
                image_name: << parameters.image_name >>
                module_name: << parameters.module_name >>
                organization: << parameters.organization >>
version: 2.1

