description: >
  Build new image
parameters:
  organization:
    type: string
    default: ""
    description: Name of the organization in Humanitec.
  module_name:
    type: string
    default: $CIRCLE_PROJECT_REPONAME
    description: Name of the module in Humanitec. The id must be all lowercase letters, numbers and the "-" symbol. It cannot start or end with "-". Defaults to $CIRCLE_PROJECT_REPONAME.
  dockerfile:
    type: string
    default: Dockerfile
    description: Name of the dockerfile to be used. Defaults to Dockerfile.
  path:
    type: string
    default: .
    description: Path to the directory containing the dockerfile. Default to . (working directory).
  build_arguments:
    type: string
    default: ""
    description: Additional build arguments.
steps:
  - run:
      name: Build docker image
      command: |
        LOCAL_TAG=<< parameters.organization >>/<< parameters.module_name >>:$CIRCLE_SHA1
        docker build \
          -t $LOCAL_TAG \
          -f << parameters.path >>/<< parameters.dockerfile >> \
          << parameters.build_arguments >> \
          << parameters.path >>
