description: >
  Build new image
parameters:
  organization:
    type: string
    default: ""
    description: Name of the organization in Humanitec.
  module_name:
    type: string
    default: ""
    description: Name of the module in Humanitec.
  dockerfile:
    type: string
    default: Dockerfile
    description: Name of the dockerfile to be used. Defaults to Dockerfile.
  path:
    type: string
    default: .
    description: Path to the directory containing the dockerfile. Default to . (working directory).
steps:
  - run:
      name: Build docker image
      command: |
        LOCAL_TAG=<< parameters.organization >>/<< parameters.module_name >>:$CIRCLE_SHA1
        docker build \
          -t $LOCAL_TAG \
          -f << parameters.path >>/<< parameters.dockerfile >> \
          << parameters.path >>
        echo docker images -q $LOCAL_TAG
